/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice;

/**
 *
 * @author vyndk
 */
public class DNAComplement {

    public static void main(String[] args) {
        String dnaComplement = dnaComplement("ACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTTACCGGGTTTT");
        System.out.println(dnaComplement);
    }

    private static String dnaComplement(String s) {
        // Reverse DNA
        String reverseDNA = new StringBuilder(s).reverse().toString();
        // Complete each element
        int length = reverseDNA.length();
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < length; i++) {
            String c = String.valueOf(reverseDNA.charAt(i));
            //Process char
            result.append(getComplement(c));
        }
        return result.toString();
    }

    private static String getComplement(String dna) {
        switch (dna) {
            case "A":
                return "T";
            case "T":
                return "A";
            case "C":
                return "G";
            case "G":
                return "C";
            default:
                return "";
        }
    }
}
